### PR TITLE
Fix output selection for the AST

### LINKED ISSUE #37: Output selection in Solidity's JSON is wrong
```
    settings: {
      optimizer: options.solc.optimizer,
      outputSelection: {
        "*": {
          "*": [
            "abi",
            "ast",
            "evm.bytecode.object",
            "evm.bytecode.sourceMap",
            "evm.deployedBytecode.object",
            "evm.deployedBytecode.sourceMap"
          ]
        },
      }
    }
```

The `ast` is not an output of a given contract, but a file, therefore it will not be matched against `*`. Please see the documentation regarding this.

The correct version should be:
```
    settings: {
      optimizer: options.solc.optimizer,
      outputSelection: {
        "*": {
          "": [
            "ast"
          ],
          "*": [
            "abi",
            "evm.bytecode.object",
            "evm.bytecode.sourceMap",
            "evm.deployedBytecode.object",
            "evm.deployedBytecode.sourceMap"
          ]
        },
      }
    }
```

### PR DESCRIPTION
**Pull request by axic**
Fixes #37.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -76,9 +76,11 @@ var compile = function(sources, options, callback) {
       optimizer: options.solc.optimizer,
       outputSelection: {
         "*": {
+          "": [
+            "legacyAST"
```
Comment (gnidan) [inline index.js:80]: Why the rename?

**Review by gnidan — COMMENTED** [review]
@axic thanks for this - question for you before I merge

**Review by gnidan — APPROVED** [review]
Oh nevermind actually - I realized `legacyAST` is what was being used
